# Travis-CI configuration for QHanoi

language: cpp

compiler: gcc

os: linux

sudo: required

services:
    - docker

install:
    - sudo apt-get install cmake qtbase5-dev libqt5svg5-dev

script:
    - mkdir build && cd build && cmake ../ && make
    - cd ..
    - docker build --build-arg USEAPTCACHER=no -t mghansen256/qhanoi -f docker/ubuntu17.10/Dockerfile .
