# Travis-CI configuration for QHanoi

language: cpp

compiler: gcc

os: linux

sudo: required

install:
    - sudo apt-get install cmake qt4-dev-tools qt4-qmake libqtcore4

script:
    - mkdir build && cd build && cmake ../ && make