# Travis-CI configuration for QHanoi

language: cpp

compiler: gcc

os: linux

sudo: required

services:
    - docker

install:
    - sudo apt-get install cmake qt4-dev-tools qt4-qmake libqtcore4

script:
    - mkdir build && cd build && cmake ../ && make

# also test building in docker container if normal build succeeded
after_success:
    - cd ..
    - docker build -t mghansen256/qhanoi docker/ubuntu16.10
