# Dockerfile to build qhanoi under ubuntu inside docker
#
# Copyright (C) 2019 Michael G. Hansen
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update

# first configure apt-get to use apt-cacher-ng if running on the host
# add --build-arg USEAPTCACHER=no to suppress looking for apt-cacher-ng
ARG USEAPTCACHER=yes
RUN if [ "$USEAPTCACHER" = "yes" ] ; then \
      apt-get install -y auto-apt-proxy ; \
    fi

# install eatmydata to speed up the installation process
RUN apt-get install -y eatmydata

# install build-tools and dependencies
RUN eatmydata apt-get -y install git cmake qtbase5-dev libqt5svg5-dev g++ ninja-build

# for later X11 access
ENV QT_X11_NO_MITSHM=1

# create source and build directories
RUN mkdir -pv /src/qhanoi && mkdir -pv /build/qhanoi-ninja

# Import the repository into the image
# Requires start of the docker command from the root of the repository!
# docker build -t qhanoi -f docker/Dockerfile-ubuntu-18.04 .
# This import is done as late as possible, because every step after ADD
# is re-run by docker if the added directory was changed since the last
# run!
ADD . /src/qhanoi

# Build from source
# add --build-arg DOBUILD=no to avoid building
ARG DOBUILD=yes
# Note: default shell in docker is "sh", not "bash". In "sh", the comparison
#       done with "=" instead of "=="!
RUN if [ "$DOBUILD" = "yes" ] ; then \
    cd /build/qhanoi-ninja && cmake -G Ninja /src/qhanoi && ninja \
    ; fi

CMD bash
