# Build qhanoi for Android inside docker
# note: start docker from qhanoi's main directory like this: sudo docker build -f docker/Dockerfile-android .
# TODO:
# - find a base image with Dockerfile source code
# - install gradle into the image. Currently, gradle is downloaded at build time and installed into the build directory.

FROM dirkhh/android-builder:5.12.03

ENV ANDROID_NDK_ROOT=/android/android-ndk-r18b \
    ANDROID_SDK_ROOT=/android/android-sdk-linux \
    JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
    QT5_ANDROID=/android/Qt/5.12.0/ \
    ANDROID_ABI=armeabi-v7a \
    QT_ARCH=armv7 \
    QT5_ANDROID_CMAKE=${QT5_ANDROID}/android_${QT_ARCH}/lib/cmake

RUN apt-get update && apt-get install -y eatmydata auto-apt-proxy

# The system version of gradle is not used by the build system yet, for some unknown reason
RUN eatmydata apt-get install -y gradle

# install Android SDK Platfrom 16
RUN cd $ANDROID_SDK_ROOT/tools/bin/ \
    && ./sdkmanager "platforms;android-16" \
    && yes | ./sdkmanager --licenses
    
RUN mkdir -p /src/build && mkdir -p /build
ADD . src/qhanoi

RUN cd /build && \
    eatmydata cmake -DCMAKE_SYSTEM_NAME="Android" \
        -DANDROID_ABI=$ANDROID_ABI \
        -DQT_ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT" \
        -DQT_ANDROID_NDK_ROOT="$ANDROID_NDK_ROOT" \
        -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_ROOT"/build/cmake/android.toolchain.cmake \
        -DANDROID_STL="c++_shared" \
        -DCMAKE_PREFIX_PATH:UNINITIALIZED="$QT5_ANDROID_CMAKE" \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_MAKE_PROGRAM="make" \
        -DQt5Gui_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Gui -DQt5Svg_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Svg \
        -DQt5Core_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Core -DQt5Xml_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Xml \
        -DQt5Widgets_DIR=${QT5_ANDROID}/android_armv7/lib/cmake/Qt5Widgets/ -DCMAKE_PREFIX_PATH=QT5_ANDROID/android_armv7/lib \
        /src/qhanoi
        
RUN cd /build && cmake --build . -- VERBOSE=1
